# example netlify.toml
[build]
command = "prisma generate && next build"
publish = ".next"

[template.environment]
COCKROACH_URL = "Database Connection String"
NEXTAUTH_URL = "NextAuth URL"
NEXTAUTH_SECRET = "NextAuth Secret"


[[plugins]]
package = "@netlify/plugin-nextjs"
